// Package roundtrip compiles the generated model package for each fixture that
// ships an input.xml and verifies that the generated types survive an
// xml.Unmarshal -> xml.Marshal -> xml.Unmarshal cycle (DeepEqual).
//
// A fixture opts in by providing tests/fixtures/<feature>/input.xml. The root
// Go type is derived from the input root element local name as <Root>+"Type".
//
// Each case writes the generated package plus a small test file into a temp
// module and runs `go test` there, so compilation of the generated code is also
// validated end-to-end.
package roundtrip

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/harald-mue/xsd-parser-go/internal/pipeline"
)

func TestRoundTrip(t *testing.T) {
	fixturesDir := fixturesDir(t)

	entries, err := os.ReadDir(fixturesDir)
	if err != nil {
		t.Fatalf("read fixtures dir: %v", err)
	}

	ran := 0
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		feature := entry.Name()
		input := filepath.Join(fixturesDir, feature, "input.xml")
		if _, err := os.Stat(input); err != nil {
			continue
		}
		schema := filepath.Join(fixturesDir, feature, "schema.xsd")
		ran++
		t.Run(feature, func(t *testing.T) {
			runRoundTrip(t, feature, schema, input)
		})
	}
	if ran == 0 {
		t.Fatalf("no fixtures with input.xml found under %s", fixturesDir)
	}
}

func runRoundTrip(t *testing.T, feature string, schema string, input string) {
	t.Helper()

	data, err := os.ReadFile(input)
	if err != nil {
		t.Fatalf("read input.xml: %v", err)
	}
	rootType, err := rootTypeName(data)
	if err != nil {
		t.Fatalf("detect root type: %v", err)
	}

	files, err := pipeline.Render([]string{schema}, "model")
	if err != nil {
		t.Fatalf("Render returned error: %v", err)
	}
	gen, ok := files["models.go"]
	if !ok {
		t.Fatalf("rendered output does not contain models.go")
	}

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "models.go"), gen, 0o644); err != nil {
		t.Fatalf("write models.go: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "roundtrip_test.go"), []byte(innerTestSource(data, rootType)), 0o644); err != nil {
		t.Fatalf("write roundtrip_test.go: %v", err)
	}

	if err := runGoTest(dir); err != nil {
		t.Fatalf("generated package round-trip failed for %s:\n%v", feature, err)
	}
}

// rootTypeName derives the Go struct type for the input root element. The
// generator names the root type as <ElementLocalName>+"Type" both for named
// type references (element "Foo" -> FooType) and anonymous complex types.
func rootTypeName(data []byte) (string, error) {
	dec := xml.NewDecoder(bytes.NewReader(data))
	for {
		tok, err := dec.Token()
		if err != nil {
			return "", fmt.Errorf("parse root element: %w", err)
		}
		if start, ok := tok.(xml.StartElement); ok {
			return goExported(start.Name.Local) + "Type", nil
		}
	}
}

// innerTestSource builds a self-contained test file in package model. The
// template uses explicit positional verbs for the two dynamic parts (inputXML
// bytes and the root type name) and escapes the literal %v/%s/%#v directives
// emitted into the generated test with %% so fmt.Sprintf leaves them intact.
func innerTestSource(input []byte, rootType string) string {
	const tpl = `// Code generated by xsd-parser-go round-trip harness; DO NOT EDIT.
package model

import (
	"encoding/xml"
	"reflect"
	"testing"
)

var inputXML = []byte(%[1]q)

func TestRoundTrip(t *testing.T) {
	var v %[2]s
	if err := xml.Unmarshal(inputXML, &v); err != nil {
		t.Fatalf("unmarshal: %%v\n%%s", err, inputXML)
	}
	out, err := xml.MarshalIndent(&v, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %%v", err)
	}
	var v2 %[2]s
	if err := xml.Unmarshal(out, &v2); err != nil {
		t.Fatalf("re-unmarshal: %%v\n%%s", err, out)
	}
	if !reflect.DeepEqual(v, v2) {
		t.Fatalf("round-trip mismatch:\nv1=%%#v\nv2=%%#v\nout=%%s", v, v2, out)
	}
}
`
	return fmt.Sprintf(tpl, string(input), rootType)
}

func runGoTest(dir string) error {
	initCmd := exec.Command("go", "mod", "init", "roundtrip")
	initCmd.Dir = dir
	if out, err := initCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("go mod init: %v\n%s", err, out)
	}

	testCmd := exec.Command("go", "test", "-count=1", ".")
	testCmd.Dir = dir
	out, err := testCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("go test failed:\n%s", out)
	}
	return nil
}

func fixturesDir(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	// tests/roundtrip -> tests/fixtures
	candidate := filepath.Join(filepath.Dir(dir), "fixtures")
	if _, err := os.Stat(candidate); err == nil {
		return candidate
	}
	t.Fatalf("fixtures directory not found relative to %s", dir)
	return ""
}

func goExported(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = []rune(strings.ToUpper(string(r[0])))[0]
	return string(r)
}
