package renderer

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/harald-mue/xsd-parser-go/internal/generator"
)

// RenderPackage renders all files in a generated Go package.
func RenderPackage(pkg generator.Package) (map[string][]byte, error) {
	files := make(map[string][]byte, len(pkg.Files))
	for _, file := range pkg.Files {
		src, err := RenderFile(file)
		if err != nil {
			return nil, err
		}
		files[file.Name] = src
	}
	return files, nil
}

// RenderFile renders one Go file and formats it with go/format.
func RenderFile(file generator.File) ([]byte, error) {
	if file.IsRuntime {
		return renderRuntimeFile(file)
	}
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by xsd-parser-go; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", file.Package)

	needsXSDScalars := file.RuntimePackage == "" && fileNeedsXSDScalarHelpers(file)
	needXML := (file.NeedsQName || file.NeedsNillable || file.NeedsAny || file.NeedsNamespacePrefixes) && file.RuntimePackage == ""
	needFmt := (file.NeedsValidate && file.RuntimePackage == "") || needsXSDScalars
	needRegexp := file.NeedsRegexp || needsXSDScalars
	needStrings := file.NeedsStrings || file.NeedsAny || fileNeedsStringFacetValidation(file) || needsXSDScalars
	needReflect := file.NeedsValidationHelper && file.RuntimePackage == ""
	for _, typ := range file.Types {
		if typ.XMLName != "" || typ.CustomXML != nil || typ.Choice != nil || typ.Mixed != nil || needsNormalPrefixMarshal(typ) || needsPresenceTracking(typ) || needsDefaultApplication(typ) || (file.ValidateOnUnmarshal && typ.Validate) {
			needXML = true
		}
		if typ.CustomXML != nil || typ.Choice != nil || typ.List != nil || typ.Mixed != nil || typ.Union != nil || len(typ.Facets) > 0 || structValidationNeedsFmt(typ) || needsPresenceTracking(typ) || (file.ValidateOnUnmarshal && typ.Validate) || normalPrefixMarshalNeedsFmt(typ) {
			needFmt = true
		}
		if typ.CustomXML != nil {
			needReflect = true
		}
	}
	if needXML || needFmt || needRegexp || needStrings || needReflect || needsXSDScalars || len(file.Imports) > 0 {
		fmt.Fprintln(&buf, "import (")
		if needsXSDScalars {
			fmt.Fprintln(&buf, "\t\"encoding/base64\"")
			fmt.Fprintln(&buf, "\t\"encoding/hex\"")
			fmt.Fprintln(&buf, "\t\"math/big\"")
			fmt.Fprintln(&buf, "\t\"time\"")
		}
		if needXML {
			fmt.Fprintln(&buf, "\t\"encoding/xml\"")
		}
		if needFmt {
			fmt.Fprintln(&buf, "\t\"fmt\"")
		}
		if needRegexp {
			fmt.Fprintln(&buf, "\t\"regexp\"")
		}
		if needStrings {
			fmt.Fprintln(&buf, "\t\"strings\"")
		}
		if needReflect {
			fmt.Fprintln(&buf, "\t\"reflect\"")
		}
		for _, imp := range file.Imports {
			if imp.Alias != "" {
				fmt.Fprintf(&buf, "\t%s %q\n", imp.Alias, imp.Path)
			} else {
				fmt.Fprintf(&buf, "\t%q\n", imp.Path)
			}
		}
		fmt.Fprintln(&buf, ")")
		fmt.Fprintln(&buf)
	}

	if needsXSDScalars {
		renderXSDScalarHelpers(&buf)
	}
	if file.RuntimePackage == "" {
		if file.NeedsQName || file.NeedsNillable {
			renderXSIConst(&buf)
		}
		if file.NeedsQName {
			renderQNameHelper(&buf)
		}
		if file.NeedsNillable {
			renderNillableHelper(&buf)
		}
		if file.NeedsAny {
			renderAnyHelper(&buf, file)
		}
	}
	if file.NeedsValidationHelper && file.RuntimePackage == "" {
		renderValidationHelper(&buf)
	}
	if fileNeedsStringFacetValidation(file) {
		renderFacetValidationHelpers(&buf)
	}
	if file.NeedsNamespacePrefixes {
		renderNamespacePrefixHelper(&buf, file)
	}

	for _, typ := range file.Types {
		if typ.Name == "" {
			continue
		}
		renderDocComment(&buf, typ.Name, typ.Documentation, "")
		switch typ.Kind {
		case "complexType":
			if typ.Alias != "" {
				if typ.AliasEqual {
					fmt.Fprintf(&buf, "type %s = %s\n\n", typ.Name, typ.Alias)
				} else {
					fmt.Fprintf(&buf, "type %s %s\n\n", typ.Name, typ.Alias)
				}
				break
			}
			renderStruct(&buf, typ)
			renderPrefixMarshal(&buf, file, typ)
			renderStructValidate(&buf, file, typ)
			renderStructUnmarshal(&buf, file, typ)
			renderMixedContent(&buf, file, typ)
			renderChoice(&buf, file, typ)
			renderMarkerMethod(&buf, typ)
			renderCustomXML(&buf, file, typ)
		case "element":
			if typ.Alias != "" {
				if typ.AliasEqual {
					fmt.Fprintf(&buf, "type %s = %s\n\n", typ.Name, typ.Alias)
				} else {
					fmt.Fprintf(&buf, "type %s %s\n\n", typ.Name, typ.Alias)
					renderElementAliasMarshal(&buf, file, typ)
					renderElementAliasUnmarshal(&buf, typ)
					renderElementAliasValidate(&buf, typ)
				}
			} else {
				renderStruct(&buf, typ)
			}
		case "simpleType":
			if typ.List != nil {
				renderListType(&buf, typ)
			} else if typ.AliasEqual && typ.Alias != "" {
				fmt.Fprintf(&buf, "type %s = %s\n\n", typ.Name, typ.Alias)
			} else {
				alias := typ.Alias
				if alias == "" {
					alias = "string"
				}
				fmt.Fprintf(&buf, "type %s %s\n\n", typ.Name, alias)
			}
			renderConsts(&buf, typ.Consts)
			renderEnumHelpers(&buf, typ)
			renderUnionValidate(&buf, file, typ)
			renderValidate(&buf, typ)
			renderMarkerMethod(&buf, typ)
		default:
			renderStruct(&buf, typ)
		}
	}

	for _, iface := range file.Interfaces {
		fmt.Fprintf(&buf, "type %s interface {\n\t%s()\n}\n\n", iface.Name, iface.MarkerMethod)
	}
	for _, reg := range file.Registries {
		renderRegistry(&buf, file, reg)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go file %s: %w", file.Name, err)
	}
	return formatted, nil
}

func renderRuntimeFile(file generator.File) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by xsd-parser-go; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", file.Package)
	fmt.Fprintln(&buf, "import (")
	fmt.Fprintln(&buf, "\t\"encoding/base64\"")
	fmt.Fprintln(&buf, "\t\"encoding/hex\"")
	fmt.Fprintln(&buf, "\t\"encoding/xml\"")
	fmt.Fprintln(&buf, "\t\"fmt\"")
	fmt.Fprintln(&buf, "\t\"math/big\"")
	fmt.Fprintln(&buf, "\t\"reflect\"")
	fmt.Fprintln(&buf, "\t\"regexp\"")
	fmt.Fprintln(&buf, "\t\"strings\"")
	fmt.Fprintln(&buf, "\t\"time\"")
	fmt.Fprintln(&buf, ")")
	fmt.Fprintln(&buf)
	renderXSIConst(&buf)
	renderQNameHelper(&buf)
	renderNillableHelper(&buf)
	renderAnyHelper(&buf, file)
	renderXSDScalarHelpers(&buf)
	renderRuntimePrefixHelper(&buf)
	renderValidationHelper(&buf)
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go runtime file %s: %w", file.Name, err)
	}
	return formatted, nil
}
